/*DROP TABLE IF EXISTS garages;
DROP TABLE IF EXISTS cars;
*/
DROP TABLE IF EXISTS users;



CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_Id INTEGER,
  Username TEXT,
  Password TEXT,
  created_at DATE DEFAULT CURRENT_TIMESTAMP,
  updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

/*CREATE TABLE garages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner TEXT,
  created_at DATE DEFAULT CURRENT_TIMESTAMP,
  updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cars (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  garage_id INTEGER,
  make TEXT,
  model TEXT,
  year INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY(garage_id) REFERENCES garages(id) ON DELETE CASCADE
);
{*/
